# dbt_project.yml
name: 'retail_de_mid'
version: '1.0.0'
config-version: 2

profile: 'retail_de_mid'   # harus match nama profile di profiles.yml

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  retail_de_mid:
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      sales:
        +materialized: table
        +schema: sales
      inventory:
        +materialized: table
        +schema: inventory