name: dbt CI

on:
  push:
    branches:
      - main

jobs:
  dbt-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dbt

    env:
      DATABRICKS_SERVER_HOSTNAME: ${{ secrets.DATABRICKS_SERVER_HOSTNAME }}
      DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DATABRICKS_CATALOG: ${{ secrets.DATABRICKS_CATALOG }}
      DATABRICKS_SCHEMA: ${{ secrets.DATABRICKS_SCHEMA }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-databricks
        run: pip install dbt-databricks==1.12.2

      - name: dbt deps
        run: dbt deps --profiles-dir .

      - name: dbt build
        run: dbt build --target dev --profiles-dir .
